Jungdaye89/chone

src/main/java/com/chone/server/ChoneApplication.java, src/main/java/com/chone/server/commons/jpa/BaseEntity.java
BaseEntity 를 추가했습니다
BaseEntity 생성 및 Application 에 `@EnableJpaAuditing` 추가
#9 
=> Feat: BaseEntity 생성 및 추가

src/main/java/com/chone/server/domains/user/domain/Role.java, src/main/java/com/chone/server/domains/user/domain/User.java
UserEntity랑 Role 추가했습니다.
UserEntity랑 Role 추가했습니다.
#11
=> Feat: UserEntity & RoleEnum 생성 및 추가

src/main/java/com/chone/server/domains/ai/domain/entity/Ai.java, src/main/java/com/chone/server/domains/review/domain/entity/Review.java
Ai, Review Entity 설계했습니다
- Ai Entity , Review Entity 생성
closed #8
=> Feat: Ai, Review Entity 설계

src/main/java/com/chone/server/domains/order/domain/Order.java, src/main/java/com/chone/server/domains/order/domain/OrderItem.java, src/main/java/com/chone/server/domains/order/domain/OrderStatus.java, src/main/java/com/chone/server/domains/order/domain/OrderType.java, src/main/java/com/chone/server/domains/payment/domain/Payment.java, src/main/java/com/chone/server/domains/payment/domain/PaymentMethod.java, src/main/java/com/chone/server/domains/payment/domain/PaymentStatus.java, src/main/java/com/chone/server/domains/user/domain/User.java
Order와 Payment 엔티티를 설계했습니다.
- Order
- OrderItem
- OrderStatus
- OrderType
- Payment
- PaymentStatus
- PaymentMethod
closed #7
=> Feature: Order 및 Payment Entity 설계

.gitignore, build.gradle, src/main/java/com/chone/server/commons/config/QuerydslConfig.java, src/main/java/com/chone/server/commons/exception/GlobalExceptionCode.java, src/main/java/com/chone/server/domains/product/domain/Product.java, src/main/java/com/chone/server/domains/store/controller/StoreController.java, src/main/java/com/chone/server/domains/store/domain/Category.java, src/main/java/com/chone/server/domains/store/domain/LegalDongCode.java, src/main/java/com/chone/server/domains/store/domain/Store.java, src/main/java/com/chone/server/domains/store/domain/StoreCategoryMap.java, src/main/java/com/chone/server/domains/store/dto/request/CreateRequestDto.java, src/main/java/com/chone/server/domains/store/dto/request/PutRequestDto.java, src/main/java/com/chone/server/domains/store/dto/response/CreateResponseDto.java, src/main/java/com/chone/server/domains/store/dto/response/PageInfoDto.java, src/main/java/com/chone/server/domains/store/dto/response/ReadResponseDto.java, src/main/java/com/chone/server/domains/store/dto/response/SearchResponseDto.java, src/main/java/com/chone/server/domains/store/exception/StoreExceptionCode.java, src/main/java/com/chone/server/domains/store/repository/CategoryRepository.java, src/main/java/com/chone/server/domains/store/repository/LegalDongCodeRepository.java, src/main/java/com/chone/server/domains/store/repository/StoreCategoryMapRepository.java, src/main/java/com/chone/server/domains/store/repository/StoreRepository.java, src/main/java/com/chone/server/domains/store/repository/custom/StoreRepositoryCustom.java, src/main/java/com/chone/server/domains/store/repository/custom/StoreRepositoryCustomImpl.java, src/main/java/com/chone/server/domains/store/service/StoreService.java
store, product entity 설계
- Product, Category, LegalDongCode, Store, StoreCategoryMap 엔티티들을 생성했습니다.
- 가게 검색에 필터검색을 지원하기 위해 QueryDSL 을 적용했습니다.
- build.gradle 에 QueryDSL 의존성을 추가했습니다.
- gitignore 에 Q엔티티들을 숨기도록 작성했습니다.
- 가게 컨트롤러에서 Create, Read 요청을 지원합니다.
- 가게 서비스에서 Create, Read 요청을 지원합니다.
- 가게 컨트롤러에서 `@PreAuthorize` 를 사용해서 권한을 검사합니다.
- QueryDSL 을 사용하기위해 커스텀 리포지토리를 생성했습니다.
- Create, Read 요청에 맞는 DTO 를 생성했습니다.
- Store 와 Category 다대다 관계를 위해 중간 테이블인 StoreCategoryMap 엔티티를 정의했습니다.
- `StoreRepositoryCustomImpl` 에서 QueryDSL 의 BooleanBuilder 를 이용해 직접 쿼리를 작성했습니다. (예상대로 안될 가능성 높음)
#14
=> Feat: store, product entity 설계

.gitignore, build.gradle, src/main/java/com/chone/server/commons/config/QuerydslConfig.java, src/main/java/com/chone/server/commons/exception/GlobalExceptionCode.java, src/main/java/com/chone/server/domains/product/domain/Product.java, src/main/java/com/chone/server/domains/store/controller/StoreController.java, src/main/java/com/chone/server/domains/store/domain/Category.java, src/main/java/com/chone/server/domains/store/domain/LegalDongCode.java, src/main/java/com/chone/server/domains/store/domain/Store.java, src/main/java/com/chone/server/domains/store/domain/StoreCategoryMap.java, src/main/java/com/chone/server/domains/store/dto/request/CreateRequestDto.java, src/main/java/com/chone/server/domains/store/dto/request/PutRequestDto.java, src/main/java/com/chone/server/domains/store/dto/request/UpdateRequestDto.java, src/main/java/com/chone/server/domains/store/dto/response/CreateResponseDto.java, src/main/java/com/chone/server/domains/store/dto/response/PageInfoDto.java, src/main/java/com/chone/server/domains/store/dto/response/ReadResponseDto.java, src/main/java/com/chone/server/domains/store/dto/response/SearchResponseDto.java, src/main/java/com/chone/server/domains/store/exception/StoreExceptionCode.java, src/main/java/com/chone/server/domains/store/repository/CategoryRepository.java, src/main/java/com/chone/server/domains/store/repository/LegalDongCodeRepository.java, src/main/java/com/chone/server/domains/store/repository/StoreCategoryMapRepository.java, src/main/java/com/chone/server/domains/store/repository/StoreRepository.java, src/main/java/com/chone/server/domains/store/repository/custom/StoreRepositoryCustom.java, src/main/java/com/chone/server/domains/store/repository/custom/StoreRepositoryCustomImpl.java, src/main/java/com/chone/server/domains/store/service/StoreService.java
가게 수정 API 추가
- OWNER 는 본인 가게만, MANAGER, MASTER 는 모든 가게 수정 가능
- 가게-카테고리 중간 테이블을 활용하여 카테고리 수정
- StoreExceptionCode 에 USER_NO_AUTH 추가
- UpdateRequestDto 추가
#21 
=> Feat: 가게 수정 API 추가

src/main/java/com/chone/server/commons/config/SecurityConfig.java, src/main/java/com/chone/server/commons/exception/GlobalExceptionCode.java, src/main/java/com/chone/server/commons/handler/GlobalExceptionHandler.java, src/main/java/com/chone/server/commons/jpa/BaseEntity.java, src/main/java/com/chone/server/domains/ai/domain/entity/Ai.java, src/main/java/com/chone/server/domains/auth/dto/CustomUserDetails.java, src/main/java/com/chone/server/domains/auth/filter/JwtFilter.java, src/main/java/com/chone/server/domains/auth/filter/LoginFilter.java, src/main/java/com/chone/server/domains/auth/service/MockUserDetailsServiceImpl.java, src/main/java/com/chone/server/domains/review/domain/entity/Review.java, src/main/java/com/chone/server/domains/store/controller/StoreController.java, src/main/java/com/chone/server/domains/store/service/StoreService.java, src/main/java/com/chone/server/domains/user/domain/User.java, src/main/java/com/chone/server/domains/user/repository/UserRepository.java, src/main/resources/sql/init/init-mock-users.sql
가게 삭제 요청 API 를 구현했습니다.
- BaseEntity 에 삭제 메서드 작성 (User 파라미터를 받음)
- StoreController 에서 deleteStore 메서드 작성
- StoreService 에서 deleteStore 메서드 작성
- 서비스내에서 권한 검사를 private 메서드로 작성
- BaseEntity 변경
- 삭제정보를 기록하기 위해 BaseEntity 에 메서드 추가
#25 
=> Feat: 가게 삭제 요청 API

src/main/java/com/chone/server/domains/order/domain/Delivery.java, src/main/java/com/chone/server/domains/order/domain/DeliveryStatus.java
배달 관련 Entity를 작성했습니다.
배달 관련 Entity를 작성했습니다.
상태로 DeliveryStatus enum을 작성했습니다.
closed #24 
=> Feat: Delivery Entity 설계

src/main/java/com/chone/server/domains/product/controller/ProductController.java, src/main/java/com/chone/server/domains/product/domain/Product.java, src/main/java/com/chone/server/domains/product/dto/request/CreateRequestDto.java, src/main/java/com/chone/server/domains/product/dto/request/UpdateRequestDto.java, src/main/java/com/chone/server/domains/product/dto/response/CreateResponseDto.java, src/main/java/com/chone/server/domains/product/dto/response/PageInfoDto.java, src/main/java/com/chone/server/domains/product/dto/response/ReadResponseDto.java, src/main/java/com/chone/server/domains/product/dto/response/SearchResponseDto.java, src/main/java/com/chone/server/domains/product/exception/ProductExceptionCode.java, src/main/java/com/chone/server/domains/product/repository/ProductRepository.java, src/main/java/com/chone/server/domains/product/repository/custom/ProductRepositoryCustom.java, src/main/java/com/chone/server/domains/product/repository/custom/ProductRepositoryCustomImpl.java, src/main/java/com/chone/server/domains/product/service/ProductService.java, src/main/java/com/chone/server/domains/store/dto/request/CreateRequestDto.java
Product 도메인 CRUD API 설계
- Product 도메인의 CRUD API 를 생성했습니다.
- QueryDSL 을 위해 ProductRepositoryCustom 을 정의했습니다.
- ProductExceptionCode 를 정의했습니다.
- Store 의 CreateRequestDto 에서 오타를 제거했습니다.
#36 
=> Feat: Product CRUD API 설계

src/main/java/com/chone/server/commons/jpa/BaseEntity.java, src/main/java/com/chone/server/domains/ai/controller/AiController.java, src/main/java/com/chone/server/domains/ai/domain/Ai.java, src/main/java/com/chone/server/domains/ai/dto/request/AiRequestDto.java, src/main/java/com/chone/server/domains/ai/dto/request/GeminiApiRequestDto.java, src/main/java/com/chone/server/domains/ai/dto/request/GeminiRequestDto.java, src/main/java/com/chone/server/domains/ai/dto/response/AiResponseDto.java, src/main/java/com/chone/server/domains/ai/dto/response/GeminiApiResponseDto.java, src/main/java/com/chone/server/domains/ai/dto/response/GeminiResponseDto.java, src/main/java/com/chone/server/domains/ai/exception/AiExceptionCode.java, src/main/java/com/chone/server/domains/ai/repository/AiRepository.java, src/main/java/com/chone/server/domains/ai/service/AiService.java, src/main/java/com/chone/server/domains/product/domain/Product.java, src/main/java/com/chone/server/domains/product/repository/ProductRepository.java, src/main/java/com/chone/server/domains/review/domain/Review.java, src/main/java/com/chone/server/domains/user/domain/User.java
Ai 요청 API 생성을 합니다
1. AI 설명 자동 생성 API 추가
- POST /api/v1/ai/generate-description 엔드포인트 생성
- Gemini AI API 호출 후 상품 설명을 자동으로 생성 및 저장
2. AI 요청 및 응답 DTO 추가
3.  AI 관련 예외 처리 추가
4. Product 엔티티 메서드 추가
- updateDescription(String description) 메서드 추가하여 AI가 생성한 설명을 업데이트하도록 변경
5. BaseEntity 메서드, 추가
- setCreatedByManually(String createdBy) 메서드 추가하여 AI 요청 시 createdBy 필드를 명시적으로 설정 가능하도록 변경
- AiService에서 SecurityContext에서 자동으로 생성자를 설정하지 못하는 오류 발생으로 인해, BaseEntity에서 createdBy를 명시적으로 설정할 수 있도록 개선하여 Mock 데이터를 활용한 테스트가 가능하도록 조정
- Test 완료
closed #19
=> Feat: Ai 요청 API 생성

src/main/java/com/chone/server/ChoneApplication.java, src/main/java/com/chone/server/commons/config/JpaConfig.java, src/main/java/com/chone/server/commons/exception/GlobalExceptionCode.java, src/main/java/com/chone/server/commons/jpa/AuditorAwareImpl.java, src/main/java/com/chone/server/commons/util/UriGeneratorUtil.java, src/main/java/com/chone/server/domains/order/controller/OrderController.java, src/main/java/com/chone/server/domains/order/domain/Delivery.java, src/main/java/com/chone/server/domains/order/domain/Order.java, src/main/java/com/chone/server/domains/order/domain/OrderItem.java, src/main/java/com/chone/server/domains/order/domain/OrderStatus.java, src/main/java/com/chone/server/domains/order/domain/vo/Price.java, src/main/java/com/chone/server/domains/order/domain/vo/Quantity.java, src/main/java/com/chone/server/domains/order/dto/request/CreateOrderRequest.java, src/main/java/com/chone/server/domains/order/dto/response/CreateOrderResponse.java, src/main/java/com/chone/server/domains/order/exception/OrderExceptionCode.java, src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderJpaRepository.java, src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderRepositoryImpl.java, src/main/java/com/chone/server/domains/order/repository/OrderRepository.java, src/main/java/com/chone/server/domains/order/service/OrderDomainService.java, src/main/java/com/chone/server/domains/order/service/OrderService.java, src/main/java/com/chone/server/domains/product/service/ProductService.java, src/main/java/com/chone/server/domains/store/service/StoreService.java, src/main/java/com/chone/server/domains/user/domain/User.java
1. 주문 생성을 위한 API 엔드포인트와 도메인 로직을 구현했습니다. 
2. 주문 생성 시 필요한  **Value Object**, **검증 로직**과 **도메인 규칙**을 정의하였습니다.
| 항목 | 내용 |
|------|------|
| 메서드 | **`POST`** |
| 경로 | `/api/v1/orders` |
| 권한 | `CUSTOMER`, `STORE_OWNER` 역할만 접근 가능 |
| 요청 | `CreateOrderRequest` (검증 어노테이션 적용) |
| 응답 | 201 Created + `CreateOrderResponse` |
| Location 헤더 | 생성된 리소스 URI |
<br/>
- `OrderService`: 주문 생성의 전체 로직을 조율
- `OrderDomainService`: 도메인 규칙 검증 및 주문 생성 로직 구현
- `OrderRepository`: 주문 영속성 관리 인터페이스 및 구현체
- `Price`: 금액 계산 및 검증
- `Quantity`: 주문 수량 검증
```java
public OrderType determineOrderType(Role userRole, CreateOrderRequest requestDto) {
return switch (userRole) {
case OWNER -> OrderType.ONLINE;
case CUSTOMER -> {
if (!hasText(requestDto.address())) {
throw new …
```
=> Feat: 주문 생성(Create) 구현

src/main/java/com/chone/server/domains/order/service/OrderDomainService.java, src/main/java/com/chone/server/domains/review/controller/ReviewController.java, src/main/java/com/chone/server/domains/review/dto/request/CreateRequestDTO.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewResponseDTO.java, src/main/java/com/chone/server/domains/review/exception/ReviewExceptionCode.java, src/main/java/com/chone/server/domains/review/repository/ReviewRepository.java, src/main/java/com/chone/server/domains/review/service/ReviewService.java
고객이 주문을 완료한 후 가게에 대한 리뷰를 작성할 수 있도록 기능을 추가하였으며,  주문 상태 검증, 중복 리뷰 방지 등의 로직을 포함하였습니다.  
- 리뷰 생성 API (`POST /api/v1/reviews`) 컨트롤러 추가
- `ReviewService`에서 주문 완료 여부 및 중복 리뷰 검증 기능 구현
- `ReviewExceptionCode` 정의하여 예외 처리 추가
- TEST
- 해당 주문에 대한 리뷰가 있을 경우
closed #41 
=> Feat: 리뷰 생성 API 구현

build.gradle, src/main/java/com/chone/server/commons/config/S3Config.java, src/main/java/com/chone/server/domains/order/service/OrderDomainService.java, src/main/java/com/chone/server/domains/review/controller/ReviewController.java, src/main/java/com/chone/server/domains/review/dto/request/CreateRequestDto.java, src/main/java/com/chone/server/domains/review/dto/request/ReviewListRequestDto.java, src/main/java/com/chone/server/domains/review/dto/response/PageInfoDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewDetailResponseDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewListResponseDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewPageResponseDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewReadResponseDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewResponseDto.java, src/main/java/com/chone/server/domains/review/exception/ReviewExceptionCode.java, src/main/java/com/chone/server/domains/review/repository/ReviewRepositoryImpl.java, src/main/java/com/chone/server/domains/review/repository/ReviewSearchRepository.java, src/main/java/com/chone/server/domains/review/service/ReviewService.java, src/main/java/com/chone/server/domains/s3/exception/S3ExceptionCode.java, src/main/java/com/chone/server/domains/s3/service/S3Service.java, src/main/java/com/chone/server/domains/store/controller/StoreController.java, src/main/java/com/chone/server/domains/store/exception/StoreExceptionCode.java, src/main/java/com/chone/server/domains/store/service/StoreService.java
- S3 이미지 업로드 서비스를 추가했습니다.
- S3 서비스를 사용하기위해서 application 파일에 다음과 같은 값을 입력해야합니다. 요청 파일 크기가 일정 이상시 `MaxUploadSizeExceededException` 을 발생시킵니다.
- 이미지 파일이 아닐 시 `S3ExceptionCode.INVALID_FILE_TYPE` 를 발생시킵니다.
```
spring:
servlet:
multipart:
max-file-size: 1MB
max-request-size: 1MB
cloud:
aws:
s3:
bucket-name: chonebucket
credentials:
access-key: {AWS 액세스 키}
secret-key: {AWS 시크릿 키}
region:
static: ap-northeast-2
```
- 이미지 업로드가 필요한 컨트롤러에서 다음과 같이 사용할 수 있습니다. (예시)
```java
@PostMapping(consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
@PreAuthorize("!hasRole('CUSTOMER')")
public ResponseEntity<CreateResponseDto> createProduct(
@AuthenticationPrincipal CustomUserDetails userDetails,
@RequestPart("data") CreateRequestDto createRequestDto,
@RequestPart("file") MultipartFile file) {
String imageUrl = …
```
=> Feat: S3 서비스 추가

src/main/java/com/chone/server/domains/order/controller/OrderController.java, src/main/java/com/chone/server/domains/order/domain/Order.java, src/main/java/com/chone/server/domains/order/dto/response/DeleteOrderResponse.java, src/main/java/com/chone/server/domains/order/exception/OrderExceptionCode.java, src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderDetailSearchRepositoryImpl.java, src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderJpaRepository.java, src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderListSearchRepositoryImpl.java, src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderRepositoryImpl.java, src/main/java/com/chone/server/domains/order/service/OrderDomainService.java, src/main/java/com/chone/server/domains/order/service/OrderService.java
사용자 역할(MANAGER, MASTER)에 따라 주문을 삭제할 수 있는 기능을 구현했습니다.
| 항목 | 내용 |
|------|------|
| 메서드 | **`DELETE`** |
| 경로 | `/api/orders/{id}` |
| 권한 | MANAGER, MASTER 역할만 접근 가능 |
| 파라미터 | `id` (주문 UUID) |
| 응답 | 200 OK + `DeleteOrderResponse` |
| 역할 | 삭제 가능 범위 |
|------|--------------|
| `MANAGER`, `MASTER` | 주문 상태가 CANCELED 또는 COMPLETED인 주문만 삭제 가능 |
<br/>
1. **Soft Delete 구현**
- `OrderItem` 엔티티에 `Order` 소프트 삭제 시 같이 소프트 삭제되도록 적용
2. **DTO 클래스 구현**
- `DeleteOrderResponse`: 삭제 처리된 주문 정보 응답 클래스
3. **Repository 계층**
- `OrderJpaRepository`: 삭제되지 않은 주문 조회를 위한 메서드 추가
- 모든 쿼리에 `deletedAt IS NULL` 조건 추가
4. **Service 계층**
- `OrderDomainService`: 삭제 가능 상태 검증 로직 구현
- `OrderService`: 주문 삭제 비즈니스 로직 구현
5. **Controller 계층**
- `DELETE /orders/{id}` 엔드포인트 구현
- `@PreAuthorize("hasAnyRole('MANAGER','MASTER')")` 권한 제어
6. …
=> Feat: 주문 삭제 기능 구현

.github/workflows/main.yml, build.gradle, src/main/java/com/chone/server/domains/review/controller/ReviewController.java, src/main/java/com/chone/server/domains/review/domain/Review.java, src/main/java/com/chone/server/domains/review/dto/request/UpdateRequestDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewUpdateResponseDto.java, src/main/java/com/chone/server/domains/review/exception/ReviewExceptionCode.java, src/main/java/com/chone/server/domains/review/service/ReviewService.java
- 리뷰를 수정할 수 있는 API를 구현했습니다.
- CUSTOMER만 본인의 리뷰를 수정할 수 있으며, 리뷰 작성 후 3일이 지나면 수정이 불가능합니다.
1. 리뷰 수정 API 컨트롤러 추가 (`ReviewController.java`)
- `PUT /api/v1/reviews/{id}` 엔드포인트 추가
2. 리뷰 수정 서비스 로직 (`ReviewService.java`)
- 로그인한 사용자가 리뷰 작성자가 맞는지 검증
- 3일이 지나면 수정 불가 예외 로직
- `Review.update()` 메서드 호출하여 수정 요청 반영
3. 리뷰 엔티티 수정 (`Review.java`)
- `update()` 메서드 추가 (`content`, `rating`, `imageUrl`, `isPublic` 수정 가능)
4. 예외 코드 추가 (`ReviewExceptionCode.java`)
- `REVIEW_FORBIDDEN_ACTION`: 리뷰 작성자가 아닌 경우 수정 불가
- `REVIEW_UPDATE_EXPIRED`: 3일 초과 수정 불가
5. DTO 추가
- `UpdateRequestDto.java`: 리뷰 수정 요청 데이터
- `ReviewUpdateResponseDto.java`: 리뷰 수정 응답
- TEST
- 수정 사항 반영 후 목록 조회
closed #44 
=> Feat: 리뷰 수정 API 구현

src/main/java/com/chone/server/commons/config/SecurityConfig.java, src/main/java/com/chone/server/commons/jwt/JwtUtil.java, src/main/java/com/chone/server/domains/auth/dto/CustomUserDetails.java, src/main/java/com/chone/server/domains/auth/dto/LoginDto.java, src/main/java/com/chone/server/domains/auth/filter/JwtFilter.java, src/main/java/com/chone/server/domains/auth/filter/LoginFilter.java, src/main/java/com/chone/server/domains/auth/service/CustomUserDetailsService.java, src/main/java/com/chone/server/domains/auth/service/MockUserDetailsServiceImpl.java, src/main/java/com/chone/server/domains/user/controller/UserController.java, src/main/java/com/chone/server/domains/user/domain/Role.java, src/main/java/com/chone/server/domains/user/domain/User.java, src/main/java/com/chone/server/domains/user/dto/request/LoginRequestDto.java, src/main/java/com/chone/server/domains/user/dto/request/SignupRequestDto.java, src/main/java/com/chone/server/domains/user/dto/request/UserRoleUpdateRequestDto.java, src/main/java/com/chone/server/domains/user/dto/request/UserUpdateRequestDto.java, src/main/java/com/chone/server/domains/user/dto/response/LoginResponseDto.java, src/main/java/com/chone/server/domains/user/dto/response/UserResponseDto.java, src/main/java/com/chone/server/domains/user/exception/UserExceptionCode.java, src/main/java/com/chone/server/domains/user/repository/UserRepository.java, src/main/java/com/chone/server/domains/user/service/UserService.java
Security와 Jwt를 활용한 Auth기능 구현했습니다.
User관련 CRUD 기능 구현했습니다.
SecrutiyConfig
JwtFilter
LoginFilter
CustomUserDetails
CustomUserDetailsService
UserRepository
UserService
UserController
UserExceptionCode
UserDTO
closed #16 #56
=> Feat: Security 설정 및 회원 CRUD 구현

.github/workflows/main.yml, src/main/java/com/chone/server/domains/s3/service/S3Service.java
- S3 서비스에 이미지 삭제 메서드 추가
- 깃허브 액션 워크플로우 주석처리
#55 
=> Feat: S3 이미지 삭제 기능 및 깃허브 액션 일시정지

src/main/java/com/chone/server/domains/product/controller/ProductController.java, src/main/java/com/chone/server/domains/product/dto/request/CreateRequestDto.java, src/main/java/com/chone/server/domains/product/dto/request/UpdateRequestDto.java, src/main/java/com/chone/server/domains/product/service/ProductService.java
- S3 서비스와 연동하여 이미지를 등록할 수 있도록 수정했습니다.
- DTO ImageUrl 필드에 `@Setter` 추가
- 컨트롤러에서 Multipart 데이터를 받을 수 있도록 수정
- 서비스에서 상품 추가, 수정, 삭제 시 이미지를 다룰 수 있도록 수정
- 상품 추가시 선택적으로 이미지 파일을 받아서 처리합니다.
- 상품 수정시 이미지 파일이 있다면 기존의 이미지를 삭제 후 등록합니다.
- 상품 수정시 이미지 파일이 없다면 기존의 이미지를 사용합니다.
- 상품 삭제시 기존의 이미지를 삭제합니다.
#47 
=> Update: Product 에 상품 이미지 기능 추가

src/main/java/com/chone/server/domains/review/controller/ReviewController.java, src/main/java/com/chone/server/domains/review/dto/request/StatisticsRequestDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewStatisticsResponseDto.java, src/main/java/com/chone/server/domains/review/repository/ReviewStatisticsRepository.java, src/main/java/com/chone/server/domains/review/repository/ReviewStatisticsRepositoryImpl.java, src/main/java/com/chone/server/domains/review/service/ReviewService.java
가게별 리뷰 통계 조회 기능을 구현하고 Soft Delete 방식을 적용하여 삭제된 리뷰는 제외한 통계 데이터를 반환합니다.
1.  ReviewStatisticsResponseDto.java
- `averageRating`: 평균 평점 (소수점 두 자리까지)
- `totalReviews`: 전체 리뷰 수
- `ratingDistribution`: 평점별 분포
- `lastUpdatedAt`: 마지막 통계 조회 시각
2. ReviewStatisticsRepositoryImpl
- `calculateAverageRating(UUID storeId)`: 평균 평점 계산
- `countTotalReviews(UUID storeId)`: 전체 리뷰 수 집계
- `countRatingDistribution(UUID storeId)`: 평점별 분포 집계
- `deletedAt IS NULL` 조건 추가 (Soft Delete 적용)
3. ReviewService.java
- `getReviewStatistics(UUID storeId)`
- 가게 존재 여부 확인 및 예외 처리 (`STORE_NOT_FOUND`)
- 평균 평점, 전체 리뷰 수, 평점별 분포 데이터 집계
- 마지막 통계 조회 시각 (`lastUpdatedAt`) 추가
4. ReviewController.java
- `@GetMapping("/statistics")`
- `@RequestParam UUID storeId`: 가게별 통계 조회
5. ReviewExceptionCode.java
- `INVALID_PARAMETER`: 잘못된 요청 파라미터
- …
=> Feat: 가게별 리뷰 통계 조회 API 구현

src/main/java/com/chone/server/domains/auth/dto/CustomUserDetails.java, src/main/java/com/chone/server/domains/user/controller/UserController.java, src/main/java/com/chone/server/domains/user/domain/User.java, src/main/java/com/chone/server/domains/user/dto/response/SearchUserResponseDto.java, src/main/java/com/chone/server/domains/user/dto/response/UserResponseDto.java, src/main/java/com/chone/server/domains/user/repository/UserRepository.java, src/main/java/com/chone/server/domains/user/repository/custom/UserRepositoryCustom.java, src/main/java/com/chone/server/domains/user/repository/custom/UserRepositoryCustomImpl.java, src/main/java/com/chone/server/domains/user/service/UserService.java
MANAGER, MASTER가 유저 조회시 페이징 처리되어 조회
특정유저를 검색할 수 있음
QueryDSL 사용
UserRepositoryCustom, UserRepositoryCustomImpl로 사용자 검색 기능 구현
탈퇴한 유저 검색 및 조회되지 않도록 수정
closed #64 #65 
=> Feat: 유저검색 및 페이지 처리

src/main/java/com/chone/server/domains/review/repository/ReviewRepositoryImpl.java
기존에 단일 정렬 코드를 다중 정렬 가능하게 리팩토링 진행했습니다.
- 필터 기능
평점 높은 순 (rating DESC)
평점 낮은 순 (rating ASC)
등록 최신 순 (createdAt DESC)
등록 오래된 순 (createdAt ASC)
업데이트 최신 순 (updatedAt DESC)
업데이트 오래된 순 (updatedAt ASC)
- CUSTOMER: 본인 작성 리뷰는 공개, 비공개 모두 보이고 나머지는 공개된 리뷰만 보임
- OWNER:
- 내 가게의 리뷰는 공개, 비공개 모두 보임
- 다른 가게의 리뷰는 공개된 것만 보임
- MANAGER, MASTER: 모든 리뷰 (공개 + 비공개) 보임
- 다중 정렬을 위해 List<OrderSpecifier<?>>에 여러 개의 정렬 조건을 추가
- jwt 사용하여 test 진행
closed #70 
=> Refactor: 다중 정렬 기능 추가

src/main/java/com/chone/server/domains/review/dto/response/ReviewDetailResponseDto.java, src/main/java/com/chone/server/domains/review/repository/ReviewDetailRepositoryImpl.java, src/main/java/com/chone/server/domains/review/repository/ReviewDetailSearchRepository.java, src/main/java/com/chone/server/domains/review/service/ReviewService.java
- ReviewListSearchRepository와 ReviewDetailSearchRepository 역할 명확화
- 단일 데이터 조회에 최적화하고, 목록 조회와 로직 분리
1. **ReviewDetailResponseDto.java**  
- isPublic 필드 추가하여 공개 여부 확인 가능하도록 수정
- from() 메서드에서 Review 엔티티에서 isPublic 값을 가져와 설정
- 권한 체크 및 validateAccess()에서 isPublic 사용 가능
2. **ReviewService.java**  
- ReviewDetailSearchRepository를 통해 상세 조회 로직 변경
- getReviewById()에서 ReviewDetailResponseDto 사용
- validateAccess()에서 isPublic 사용하여 권한 체크 강화
- Lazy Loading 방지 및 단일 데이터 조회 최적화
3. **ReviewDetailSearchRepository.java**  
- 단일 데이터 조회 전용 레포지토리 분리
4. **ReviewDetailRepositoryImpl.java**  
- QueryDSL 적용 및 fetchJoin() 사용하여 Lazy Loading 방지
- ReviewDetailResponseDto로 바로 변환하여 반환
- Review 목록 조회와 상세 조회의 역할이 모호한 문제 해결
- Lazy Loading 발생으로 인한 성능 저하 방지
closed #75 
=> Refactor: Review 상세 조회 로직 리팩토링

src/main/java/com/chone/server/commons/facade/ReviewFacade.java, src/main/java/com/chone/server/domains/review/facade/ReviewFacadeImpl.java, src/main/java/com/chone/server/domains/review/repository/ReviewRepository.java, src/main/java/com/chone/server/domains/review/repository/ReviewRepositoryCustom.java, src/main/java/com/chone/server/domains/review/repository/ReviewRepositoryImpl.java, src/main/java/com/chone/server/domains/review/repository/ReviewSearchRepositoryImpl.java, src/main/java/com/chone/server/domains/review/service/ReviewService.java
userId로 해당 유저가 작성한 전체 리뷰 목록을 리스트 형식으로 한 번에 조회할 수 있는 기능 추가했습니다.
- ReviewFacade 및 ReviewFacadeImpl 생성
- findReviewsByUserId(Long userId) 메서드 추가
- ReviewRepositoryCustom 및 ReviewRepositoryImpl 생성
- findAllByUserId(Long userId) 커스텀 쿼리 적용
- ReviewService 
- ReviewFacade를 통해 리뷰 리스트 조회
- getReviewsByUserId(Long userId, CustomUserDetails principal) 메서드 추가
- User ID로 해당 user가 작성한 리뷰 리스트를 한 번에 가져올 수 있도록 기능 추가
closed #80 
=> Feat: User ID로 전체 리뷰 조회

src/main/java/com/chone/server/commons/facade/ReviewFacade.java, src/main/java/com/chone/server/domains/review/controller/ReviewController.java, src/main/java/com/chone/server/domains/review/facade/ReviewFacadeImpl.java, src/main/java/com/chone/server/domains/review/infrastructure/jpa/ReviewDetailRepositoryImpl.java, src/main/java/com/chone/server/domains/review/infrastructure/jpa/ReviewRepositoryImpl.java, src/main/java/com/chone/server/domains/review/infrastructure/jpa/ReviewSearchRepositoryImpl.java, src/main/java/com/chone/server/domains/review/infrastructure/jpa/ReviewStatisticsRepositoryImpl.java, src/main/java/com/chone/server/domains/review/service/ReviewService.java
- 순환 참조 문제 해결 및 결합도 감소를 위해 Facade Pattern 적용하여 리팩토링합니다.
- ReviewService에서 Facade Pattern 사용하도록 수정
- ReviewController에 User ID로 리뷰 조회 기능 추가
closed #82 
=> Refactor: Review Facade Pattern 적용

src/main/java/com/chone/server/domains/payment/controller/PaymentController.java, src/main/java/com/chone/server/domains/payment/dto/response/PaymentDetailResponse.java, src/main/java/com/chone/server/domains/payment/exception/PaymentExceptionCode.java, src/main/java/com/chone/server/domains/payment/infrastructure/jpa/PaymentJpaRepository.java, src/main/java/com/chone/server/domains/payment/infrastructure/jpa/PaymentRepositoryImpl.java, src/main/java/com/chone/server/domains/payment/repository/PaymentRepository.java, src/main/java/com/chone/server/domains/payment/repository/dto/PaymentDetailDto.java, src/main/java/com/chone/server/domains/payment/service/PaymentDomainService.java, src/main/java/com/chone/server/domains/payment/service/PaymentService.java, src/main/java/com/chone/server/domains/user/domain/User.java
결제 상세 정보를 조회할 수 있는 API를 구현했습니다. 사용자 역할(고객, 가게 주인, 관리자/마스터)에 따라 적절한 권한으로 결제 및 관련 주문 정보를 조회할 수 있습니다.
| 항목 | 내용 |
|------|------|
| 메서드 | **`GET`** |
| 경로 | `/api/payments/{id}` |
| 권한 | 모든 역할 접근 가능 (역할별 조회 범위 제한) |
| 파라미터 | `id` (결제 UUID) |
| 응답 | 200 OK + `PaymentDetailResponse` |
| 역할 | 조회 가능 범위 |
|------|--------------|
| `CUSTOMER` | 자신의 결제만 조회 |
| `OWNER` | 자신의 매장 결제만 조회 |
| `MANAGER`, `MASTER` | 모든 결제 조회 |
<br/>
1. **DTO 클래스 구현**
- `PaymentDetailResponse`: 결제 및 주문 상세 정보를 위한 응답 클래스
- 중첩 Record 구조(`PaymentResponse`, `OrderResponse`)로 설계
- 결제 정보와 주문 정보를 함께 제공하는 구조
2. **Controller 계층**
- `GET /payments/{id}` 엔드포인트 구현
- 인증된 사용자 정보 활용
3. **Service 계층**
- 사용자 역할에 따른 조회 권한 검증 로직 구현
- `DomainService`를 통한 비즈니스 규칙 분리
4. **Repository 계층 구조화**
- `PaymentRepository`: 결제 조회 인터페이스 정의
- …
=> Feat: 결제 내역 상세 조회 기능 구현

src/main/java/com/chone/server/commons/facade/ProductFacade.java, src/main/java/com/chone/server/commons/facade/StoreFacade.java, src/main/java/com/chone/server/domains/order/service/OrderService.java, src/main/java/com/chone/server/domains/product/controller/ProductController.java, src/main/java/com/chone/server/domains/product/facade/ProductFacadeImpl.java, src/main/java/com/chone/server/domains/product/repository/ProductRepository.java, src/main/java/com/chone/server/domains/product/service/ProductService.java, src/main/java/com/chone/server/domains/store/controller/StoreController.java, src/main/java/com/chone/server/domains/store/facade/StoreFacadeImpl.java, src/main/java/com/chone/server/domains/store/repository/StoreRepository.java, src/main/java/com/chone/server/domains/store/service/StoreService.java, src/main/java/com/chone/server/domains/user/service/UserService.java
- Product, Store 도메인에 Facade 패턴 적용
- ProductFacade, StoreFacade 인터페이스 작성
- 각 도메인의 facade 디렉토리에 구현체 생성
- 서비스에서 facade 호출
#77 
=> Feat: Product, Store 도메인에 Facade 패턴 적용

src/main/java/com/chone/server/commons/facade/OrderFacade.java, src/main/java/com/chone/server/commons/facade/ReviewFacade.java, src/main/java/com/chone/server/domains/order/facade/OrderFacadeImpl.java, src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderJpaRepository.java, src/main/java/com/chone/server/domains/order/infrastructure/jpa/OrderRepositoryImpl.java, src/main/java/com/chone/server/domains/order/repository/OrderRepository.java, src/main/java/com/chone/server/domains/review/facade/ReviewFacadeImpl.java, src/main/java/com/chone/server/domains/user/service/UserService.java
User삭제시 연관데이터도 함께 삭제
1. UserFacade 추가
2. UserFacadeImpl 추가
3. ReviewFacade 인터페이스에 deleteReview와 findAllReviews추가
4. ReviewFacadeImpl에 추가된 메서드 구현
5. OrderFacade 인터페이스 추가
6. OrderFacadeImpl 추가
7. OrderRepository, OrderRepositoryImpl, OrderJpaRepository에 UserId로 Order찾는 거 추가
일단 코드는 짰는데 데이터가 없어서 테스트는 아직임
일단 서버 실행은 돌아감
Order를 손대긴 했는데 구조가 수빈님이 하신 구조에 맞게 했는지 모르겠음
확인 부탁드려요 @Soobinnni 
closed #90
=> Feat: User삭제시 연관데이터도 함께 삭제

src/main/java/com/chone/server/commons/facade/DeliveryFacade.java, src/main/java/com/chone/server/domains/delivery/exception/DeliveryExceptionCode.java, src/main/java/com/chone/server/domains/delivery/facade/DeliveryFacadeImpl.java, src/main/java/com/chone/server/domains/delivery/infrastructure/DeliveryJpaRepository.java, src/main/java/com/chone/server/domains/delivery/infrastructure/DeliveryRepositoryImpl.java, src/main/java/com/chone/server/domains/delivery/repsitory/DeliveryRepository.java, src/main/java/com/chone/server/domains/order/controller/OrderController.java, src/main/java/com/chone/server/domains/order/domain/Delivery.java, src/main/java/com/chone/server/domains/order/domain/Order.java, src/main/java/com/chone/server/domains/order/domain/OrderStatus.java, src/main/java/com/chone/server/domains/order/dto/request/OrderStatusUpdateRequest.java, src/main/java/com/chone/server/domains/order/dto/response/OrderStatusUpdateResponse.java, src/main/java/com/chone/server/domains/order/exception/OrderExceptionCode.java, src/main/java/com/chone/server/domains/order/service/OrderDomainService.java, src/main/java/com/chone/server/domains/order/service/OrderService.java
1. 주문 상태를 변경할 수 있는 API 엔드포인트와 도메인 로직을 구현했습니다.
2. 주문 상태별 배달 정보 처리 로직을 구현했습니다.
3. 상태 변경 시 필요한 **권한 검증**, **상태 전환 검증**, **도메인 규칙**을 정의했습니다.
| 항목 | 내용 |
|------|------|
| 메서드 | **`PATCH`** |
| 경로 | `/api/v1/orders/{id}/status` |
| 권한 | `CUSTOMER` 역할 제외, 가게 주인은 본인 가게 주문만 가능 |
| 요청 | `OrderStatusUpdateRequest` (검증 어노테이션 적용) |
| 응답 | 200 OK + `OrderStatusUpdateResponse` |
<br/>
- `OrderStatus` 열거형에 상태 순서(step) 개념 도입
- 상태 검증 헬퍼 메서드 추가 (`isProgressableFrom`, `isValidForOfflineOrder`, `isTerminal`)
- `OrderDomainService`에 권한 및 상태 변경 검증 로직 추가
- `DeliveryFacade`에 `findByOrderOrNull` 메서드 추가
- 주문 상태별 배달 처리 로직 구현
```java
public void validateOrderStatusChangePermission(User user, Order order) {
if (user.getRole() == Role.OWNER) {
if (!order.getStore().getUser().getId().equals(user.getId())) {
throw new …
```
=> Feat: 주문 상태 변경 및 배달 상태 변경 기능 구현

src/main/java/com/chone/server/commons/facade/AiFacade.java, src/main/java/com/chone/server/commons/facade/ProductFacade.java, src/main/java/com/chone/server/commons/facade/ReviewFacade.java, src/main/java/com/chone/server/domains/ai/facade/AiFacadeImpl.java, src/main/java/com/chone/server/domains/ai/service/AiService.java, src/main/java/com/chone/server/domains/product/facade/ProductFacadeImpl.java, src/main/java/com/chone/server/domains/review/facade/ReviewFacadeImpl.java, src/main/java/com/chone/server/domains/review/service/ReviewService.java
Ai, Review에 Facade 패턴 적용했습니다.
1. StoreFacade 적용
- findStoreById()로 StoreRepository에 직접 접근하지 않고 의존성 제거
2. OrderFacade 적용
- findById()로 Order 엔티티 조회
- validateOrderOwnership()와 validateOrderStatus()
- 주문 소유자 검증 및 주문 상태 검증 로직을 Facade에서 통일화
3. ReviewFacade 적용
- findReviewById()와 findByOrderId()
- Soft Delete 조건이 적용된 조회를 Facade에서 일관성 있게 관리
4. ProductFacade 구현 및 적용
- Product findByIdAndStoreUser(UUID productId, User user)  
- 현재 사용자에게 속한 Product를 조회하고, 없으면 예외 발생
- 소유자 검증을 포함하여 비즈니스 규칙을 Facade에 캡슐화
- void updateDescription(Product product, String description)  
- Product 설명 업데이트
- 비즈니스 규칙에 따라 설명 길이 제한이나 특수문자 처리가 추가될 수 있으므로 Facade에 포함
5. AiFacade 구현 및 적용
- Ai saveAiRecord(Product product, User user, String requestText, String responseText)  
- AI 기록을 저장
- Builder 패턴을 사용하고 작성자 정보 추가 등의 비즈니스 로직을 …
=> Refactor: Ai, Review에 Facade 패턴 적용 및 비즈니스 로직 리팩토링

src/main/java/com/chone/server/domains/product/controller/ProductController.java, src/main/java/com/chone/server/domains/product/service/ProductService.java, src/main/java/com/chone/server/domains/store/controller/StoreController.java
- Product, Store Controller 에 Swagger 설명을 추가했습니다.
- Product Service 에서 이미지 파일 없이 요청할 때 처리하는 로직을 수정했습니다.
#92 
=> Docs: Product, Store Swagger 설명 추가

src/main/java/com/chone/server/domains/ai/controller/AiController.java, src/main/java/com/chone/server/domains/ai/dto/request/AiRequestDto.java, src/main/java/com/chone/server/domains/ai/dto/request/GeminiApiRequestDto.java, src/main/java/com/chone/server/domains/ai/dto/request/GeminiRequestDto.java, src/main/java/com/chone/server/domains/ai/dto/response/AiResponseDto.java, src/main/java/com/chone/server/domains/ai/dto/response/GeminiApiResponseDto.java, src/main/java/com/chone/server/domains/ai/dto/response/GeminiResponseDto.java, src/main/java/com/chone/server/domains/review/controller/ReviewController.java, src/main/java/com/chone/server/domains/review/dto/request/CreateRequestDto.java, src/main/java/com/chone/server/domains/review/dto/request/DeleteRequestDto.java, src/main/java/com/chone/server/domains/review/dto/request/ReviewListRequestDto.java, src/main/java/com/chone/server/domains/review/dto/request/StatisticsRequestDto.java, src/main/java/com/chone/server/domains/review/dto/request/UpdateRequestDto.java, src/main/java/com/chone/server/domains/review/dto/response/PageInfoDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewDeleteResponseDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewDetailResponseDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewListResponseDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewPageResponseDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewReadResponseDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewResponseDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewStatisticsResponseDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewUpdateResponseDto.java, src/main/resources/application.yml
Resolved #99
Ai, Review Swagger 문서화 작업했습니다.
closed #99 
=> Docs: Ai, Review Swagger 문서화 작업

src/main/java/com/chone/server/domains/s3/service/S3Service.java
- S3 에서 이미지 삭제시 null URL 을 받으면 반환처리하도록 수정
#57 
=> Update: S3 에서 이미지 삭제시 null 처리 추가

src/main/java/com/chone/server/domains/review/controller/ReviewController.java, src/main/java/com/chone/server/domains/review/dto/request/ReviewListRequestDto.java, src/main/java/com/chone/server/domains/review/facade/ReviewFacadeImpl.java, src/main/java/com/chone/server/domains/review/service/ReviewService.java
- 이미지 업로드 시 S3 연결 및 page default 처리하도록 코드 개선했습니다
- createReview() 및 updateReview()에서 MultipartFile로 이미지 파일을 받아 S3에 업로드하도록 수정
- ReviewListRequestDto에서 page와 size의 기본값을 설정
- page = 0 (기본값)
- size = 10 (기본값)
closed #105 
=> Fix: 이미지 S3 업로드 및 페이징 기본값 설정

src/main/java/com/chone/server/domains/product/dto/request/CreateRequestDto.java, src/main/java/com/chone/server/domains/product/dto/request/UpdateRequestDto.java, src/main/java/com/chone/server/domains/product/dto/response/CreateResponseDto.java, src/main/java/com/chone/server/domains/product/dto/response/PageInfoDto.java, src/main/java/com/chone/server/domains/product/dto/response/ReadResponseDto.java, src/main/java/com/chone/server/domains/product/dto/response/SearchResponseDto.java, src/main/java/com/chone/server/domains/store/dto/request/CreateRequestDto.java, src/main/java/com/chone/server/domains/store/dto/request/UpdateRequestDto.java, src/main/java/com/chone/server/domains/store/dto/response/CreateResponseDto.java, src/main/java/com/chone/server/domains/store/dto/response/PageInfoDto.java, src/main/java/com/chone/server/domains/store/dto/response/ReadResponseDto.java, src/main/java/com/chone/server/domains/store/dto/response/SearchResponseDto.java
- Product, Store 도메인의 DTO에 Swagger 주석을 추가했습니다.
- Store의 조회 응답 DTO 에 전화번호를 추가했습니다.
#103 
=> Refactor: Product, Store DTO 수정

build.gradle, src/main/java/com/chone/server/domains/ai/controller/AiController.java, src/main/java/com/chone/server/domains/ai/dto/request/AiRequestDto.java, src/main/java/com/chone/server/domains/review/controller/ReviewController.java, src/main/java/com/chone/server/domains/review/dto/request/CreateRequestDto.java, src/main/java/com/chone/server/domains/review/dto/request/ReviewListRequestDto.java, src/main/java/com/chone/server/domains/review/dto/response/ReviewPageResponseDto.java, src/main/java/com/chone/server/domains/review/service/ReviewService.java, src/test/java/com/chone/server/domains/ai/controller/AiControllerTest.java, src/test/java/com/chone/server/domains/review/controller/ReviewControllerTest.java
- Ai, Review Test Code 작성과 코드 리팩토링하였습니다.
1. @ModelAttribute 사용한 Pageable 리팩토링
- @ModelAttribute를 통해 Pageable 객체 자동 바인딩
- page 및 size 파라미터가 없거나 유효하지 않은 경우 기본값 설정
2. ReviewListRequestDto 개선
- page 및 size 파라미터가 null 또는 비정상 값일 경우 기본값 설정
3. DTO에 isPublic 필드 추가 및 Service 수정
- isPublic 필드를 true 하드코딩에서 request.getIsPublic()에서 가져오는 것으로 수정
4. 페이지네이션에서 연관 엔티티 조회가 있을 경우 발생되는 N+1  문제를 해결하기 위해 사용한 fetchJoin()를 N+1 발생될 수 있는 코드에 모두 적용
N+1 문제를 해결하기 위해 fetchJoin()을 사용했습니다. 해당 코드를 TEST 해보고 싶어서 TEST CODE를 작성했으나, eq(null) is not allowed 에러가 계속적으로 발생해 하지 못했습니다. 해결 방법을 아신다면 알려주세요...!
closed #112
=> Test: Ai, Review Test Code 및 코드 리팩토링

src/main/java/com/chone/server/commons/facade/ReviewFacade.java, src/main/java/com/chone/server/domains/review/facade/ReviewFacadeImpl.java, src/main/java/com/chone/server/domains/review/service/ReviewService.java
ReviewStatisticsResponseDto getReviewStatistics(UUID storeId) 메서드를 Facade로 이동하여 공통 로직으로 관리합니다
ReviewStatisticsResponseDto getReviewStatistics(UUID storeId) 메서드를 Facade로 이동
closed #<이슈 번호>
=> Refactor: Review 통계 로직 Facade로 리팩토링

src/main/java/com/chone/server/commons/facade/ReviewFacade.java, src/main/java/com/chone/server/domains/order/dto/request/CreateOrderRequest.java, src/main/java/com/chone/server/domains/payment/dto/request/CreatePaymentRequest.java, src/main/java/com/chone/server/domains/review/facade/ReviewFacadeImpl.java, src/main/java/com/chone/server/domains/review/infrastructure/jpa/ReviewRepositoryImpl.java, src/main/java/com/chone/server/domains/review/infrastructure/jpa/ReviewSearchRepositoryImpl.java, src/main/java/com/chone/server/domains/review/service/ReviewService.java, src/main/java/com/chone/server/domains/store/controller/StoreController.java, src/main/java/com/chone/server/domains/store/dto/response/ReadResponseDto.java, src/main/java/com/chone/server/domains/store/repository/custom/StoreRepositoryCustom.java, src/main/java/com/chone/server/domains/store/repository/custom/StoreRepositoryCustomImpl.java, src/main/java/com/chone/server/domains/store/service/StoreService.java, src/main/java/com/chone/server/domains/user/domain/User.java, src/test/java/com/chone/server/domains/product/service/ProductServiceTest.java, src/test/java/com/chone/server/domains/user/controller/UserControllerTest.java
- N + 1 문제를 해결하고 검색 기능에 평점순 필터를 활용하기 위해 Querydsl 를 수정했습니다.
- 조회 DTO 에 평균 평점 필드를 추가했습니다.
- 상세조회 API를 위해서, 가게에 대한 평균 평점을 가져오는 Facade 메서드가 필요합니다.
=> Feature: 가게 평균 평점 조회기능

src/test/java/com/chone/server/domains/product/service/ProductServiceTest.java
- Product 서비스의 createProduct 메서드 테스트 코드를 작성했습니다.
- 성공
- 이미지 파일 있음
- 이미지 파일 없음
- 실패
- 가게 없음
- 점주 아님
=> Feat: Product 서비스 테스트 코드
